#!/bin/bash
service ssh start
nginx &
for (( ; ; ))
do
   >&2 echo "$(date) I am still here ... "
   echo "Hi there! I am just writing out a bunch of stuff here to fill up logs."
   
   echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam venenatis dictum metus quis tincidunt. Donec accumsan semper mi a vestibulum. In rutrum lorem vel efficitur lacinia. Vivamus blandit nibh at mi gravida pellentesque. Fusce in augue eu orci fringilla tempor et ut massa. Ut bibendum felis maximus accumsan iaculis. Mauris non nisl massa. Vivamus commodo, velit sit amet dictum mattis, erat dui varius felis, in consequat magna odio et nisl. Mauris suscipit velit nec ultrices tincidunt. Vestibulum eget sem est. Sed nec leo dolor. Pellentesque sed lacus scelerisque, rutrum arcu a, fermentum diam. Proin porttitor eros ac erat semper venenatis. Cras quis ultricies nunc. Sed id lorem eu est rutrum ultrices quis sit amet eros."
   echo "Sed ut fringilla dui. Ut non libero risus. Morbi quis venenatis lacus, at auctor nisl. Sed pellentesque odio sed lacus scelerisque consectetur. Donec diam leo, euismod id libero scelerisque, pharetra rhoncus justo. Donec ullamcorper nulla felis, quis tristique felis pulvinar eget. Etiam consectetur pellentesque mauris vitae volutpat. Phasellus pharetra urna mollis ligula auctor, et vestibulum erat eleifend. Ut aliquet ante id augue scelerisque venenatis. Duis non risus ut felis sodales ornare at a ex. Fusce condimentum et est in sodales. Cras non venenatis tortor. Pellentesque laoreet magna a lectus tincidunt hendrerit. Fusce congue, elit aliquet sodales semper, velit nulla auctor ex, sed commodo mi tellus sit amet enim. Cras suscipit volutpat dolor, at sollicitudin felis ullamcorper eget."
   echo "Suspendisse dapibus leo vel faucibus scelerisque. Duis nec volutpat risus. Quisque eros ex, sollicitudin eu efficitur non, accumsan eget metus. Vivamus sollicitudin odio ac fringilla vulputate. Sed nec scelerisque nulla, consectetur volutpat elit. Morbi dignissim non tellus ac semper. Phasellus at nulla consectetur, elementum ante non, tristique nibh. Aenean at hendrerit arcu, eu rhoncus massa. In dapibus nibh quis massa sollicitudin venenatis convallis et nisl. Praesent elit ex, sagittis vel justo at, maximus tempor felis. Ut aliquet lorem sit amet elit rhoncus, ut dictum nulla efficitur. Aliquam erat volutpat. Duis accumsan ex arcu, eu accumsan magna gravida id. Vivamus volutpat eros ultricies ligula posuere vehicula."
   echo "Sed varius, sapien non rutrum ullamcorper, orci quam eleifend dolor, ornare dignissim odio nibh sed odio. Etiam nulla turpis, pulvinar in urna ac, sodales ullamcorper lorem. Pellentesque eu tincidunt ipsum. Cras rhoncus lacus quis ligula dignissim, ac cursus augue consequat. Suspendisse a neque interdum, lobortis ipsum sed, iaculis ex. Nullam varius consectetur magna eget scelerisque. Curabitur commodo sem eu velit ultricies, quis sodales nisl rutrum. Vestibulum dapibus tempus arcu, vel volutpat nisi cursus eget."
   echo "Donec eu nunc vel dui laoreet iaculis eget at libero. Vivamus sed posuere leo. Integer vitae ex nisl. Nullam pellentesque turpis purus, et dictum dolor luctus quis. Quisque pharetra risus sed eros iaculis suscipit et vitae tortor. Aliquam id luctus odio. In aliquet sollicitudin est, quis fringilla elit placerat nec. Sed vel dignissim massa. Quisque maximus sed purus at ornare. Morbi aliquet enim aliquet, dignissim risus et, convallis justo. Sed vel scelerisque risus. Donec hendrerit, ante non rutrum egestas, nisl metus molestie eros, quis malesuada lacus neque quis justo. Maecenas lobortis felis a risus interdum, eget malesuada odio vulputate. Nulla in dolor quam. Praesent lectus neque, feugiat id nulla quis, maximus placerat justo."
   sleep 10
done
